ru:
 first_start_input: "Привет, %s!\n
 Выбери тип расписания из меню! Можешь не торопится, мы нанели Ждуна обраьатовать запросы."
 repeating_start_input: "Астановитесь, %s!\n
 Слишко много работы может растроить Ждуна! \nВыбери тип расписания."
 choose_option: "Выбери тип расписания из списка кнопок"
 help: "Здарова сталкер!\n А если ты девушка то,Привет красавица!\n
 Этот бот сделан группой энтузиастов для студетов и хорошых учителей USARB.\n
 Пока что бот поддерживает следующие команды:\n
 /studyPlan -- см. учебный план (в настоящее время поддерживаются только группы ME13M и DM11M)\n
 /penis -- генерирует *****\n
 Другие команды в разработке.\n
 {\nЧерный список @UsarbOrarBot:\n Zastanceanu Liubov\n}"
 no_response: "По данному запросу ничего не найдено."
 get_group: "Введите навзание группы."
 get_teacher: "Введите имя учителя."
 get_audience: "Введите кабинет."
 choose_semester: "Выбери семестр."
 wrong_command: "Эта команда пока не поддерживается"
 button:
  semester_I: "Семестр I"
  semester_II: "Семестр II"
  +1day: "+1День"
  +2day's: "+2Дня"
  +week: "+Неделя"

en:
 first_start_input: "Hey! %s!\n
 Choose the type of schedule from the menu! You can take your time, we hired Zhdun to process requests."
 repeating_start_input: "Stop! %s!\n
 Too much work can upset Zhdun!\nChoose the type of schedule."
 choose_option: "Select the type of schedule from the list of buttons"
 help: "Hy stalker!\n
 And if you are a girl then, Hello, beauty!\n
 This bot was made by a group of enthusiasts for USARB students and good teachers.\n
 So far, the bot supports the following commands:\n
 /studyPlan -- see study plan (currently only supports groups ME13M ang DM11M)\n
 /penis -- generates your *****\n
 More commands are under development.\n
 {\n @UsarbOrarBot Blacklist: \\ n Zastanceanu Liubov \n}"
 no_response: "No results were found for this request."
 get_group: "Enter your group."
 get_teacher: "Enter teacher's name."
 get_audience: "Enter audience."
 choose_semester: "Choose Semester."
 wrong_command: "This command is not yet supported."
 button:
  semester_I: "Semester I"
  semester_II: "Semester II"
  +1day: "+1day"
  +2day's: "+2day's"
  +week: "nextWeek"

ro:
 first_start_input: "Privet! %s!\n
 Alege un tipul operatiei din meniu! Nu te tarapi ia-ți timpul,\nl-am angajat pe Zhdun să proceseze cererile."
 repeating_start_input: "Stop! %s!\n
 Prea multă muncă poate abiji pe Zhdun!\nAlegeți tipul de program."
 choose_option: "Alege tipul orarului!\n Indiciu: Din butoane!"
 help: "Cimok în pupok stalker!\n
 Și dacă ești fată, atunci, Bună frumusețe!\n
 Acest bot a fost creat de un grup de entuziaști (bine, baza a fost pusă de @tetragramatonn dar la măreţie a fost adus de @MihaiCojusnean)\n
 pentru studenții USARB și profesorii buni.\n
 Până în prezent, botul acceptă următoarele comenzi:\n
 /studyPlan -- vezi planul de studiu (la moment suportă doar grupele ME13M și DM11M)\n
 /penis -- generează un *****\n
 Până o să apara alete comenzi mai aveți de mâncat măligă.\n
 Totul abia începe! Vseo toliko nacinaetse\n
 {\n @UsarbOrarBot Lista neagră: \n Zastanceanu Liubov (Da ăto jestko)\n}"
 no_response: "Nu s-au găsit rezultate pentru această solicitare."
 get_group: "Scrie denumirea grupei."
 get_teacher: "Scrie numele profesorului (cu ș/ț/â/ă/î dacă e cazul)."
 get_audience: "Scrie nr/denumirea cabinenutului."
 choose_semester: "Alege semestrul."
 wrong_command: "Această comandă nu se suștine la moment :(."
 button:
  semester_I: "Semestru I"
  semester_II: "Semestru II"
  +1day: "+1Zi"
  +2day's: "+2Zile"
  +week: "+1Săptămână"

fr:
 first_start_input: "Hé! %s!\n
 Choisissez le type d'horaire dans le menu! Vous pouvez prendre votre temps,
 nous avons engagé Zhdun pour traiter les demandes."
 repeating_start_input: "Arrêtez, %s!\n Trop de travail peut déranger Zhdun!\n
 Choisissez le type d'horaire."
 choose_option: "Sélectionnez le type d'horaire dans la liste des boutons."
 help: "Bonjour Stalker!\nEt si vous êtes une fille alors, Bonjour, beauté!\n
 Ce bot a été créé par un groupe de passionnés pour les étudiants de l'USARB et les bons professeurs.\n
 Jusqu'à présent, le bot prend en charge les commandes suivantes:\n
 /studyPlan -- voir le plan d'étude (ne prend actuellement en charge que les groupes ME13M est DM11M)\n
 /penis -- génère un *****\n
 D'autres commandes sont en cours de développement.\n
 {\n @UsarbOrarBot Liste noire: \\ n Zastanceanu Liubov \n}"
 no_response: "Aucun résultat n'a été trouvé pour cette demande."
 get_group: "Entrez le nom du groupe."
 get_teacher: "Entrez le nom de l'enseignant."
 get_audience: "Entrez le numéro de la chambre."
 choose_semester: "Choisissez un semestre."
 wrong_command: "Cette commande n'est pas encore prise en charge."
 button:
  semester_I: "Semestere I"
  semester_II: "Semestere II"
  +1day: "+1Jour"
  +2day's: "+2Jours"
  +week: "+1Semaine"